---

- name: Enable fastestmirror on Fedora
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: fastestmirror
    value: "1"
  when:
    - ansible_distribution == 'Fedora'

- name: Disable install_weak_deps on Fedora
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: install_weak_deps
    value: "0"
  when:
    - ansible_distribution == 'Fedora'

- name: Ensure all packages are updated
  package:
    name: "*"
    state: latest
  register: package_updates
  until: package_updates is success
  retries: 5
  when: update_all_packages

- name: Install required packages
  package:
    name: "{{ required_packages }}"
  register: package_install
  until: package_install is success
  retries: 5
  tags:
    - always

- name: Set global gitconfig parameters
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - name: user.name
      value: "Integration Testing"
    - name: user.email
      value: "nobody@redhat.com"

- name: Ensure cloned repo directories are completely clean
  file:
    path: "/opt/{{ item }}"
    state: absent
  loop:
    - osbuild
    - osbuild-composer
    - cockpit-composer

- name: Clone osbuild from GitHub
  git:
    repo: "{{ osbuild_repo }}"
    dest: /opt/osbuild
    version: "{{ osbuild_version }}"
    refspec: "{{ osbuild_ref }}"
    force: yes
    clone: yes
    update: yes
    track_submodules: no

- name: Clone osbuild-composer from GitHub
  git:
    repo: "{{ osbuild_composer_repo }}"
    dest: /opt/osbuild-composer
    version: "{{ osbuild_composer_version }}"
    refspec: "{{ osbuild_composer_ref }}"
    force: yes
    clone: yes
    update: yes
    track_submodules: no

- name: Clone cockpit-composer from GitHub
  git:
    repo: "{{ cockpit_composer_repo }}"
    dest: /opt/cockpit-composer
    version: "{{ cockpit_composer_version }}"
    refspec: "{{ cockpit_composer_ref }}"
    force: yes
    clone: yes
    update: yes
    track_submodules: no
  when: install_cockpit_composer_from_git

- name: Install build dependencies
  command: |
    dnf -y builddep \
      /opt/osbuild-composer/osbuild-composer.spec \
      /opt/osbuild/osbuild.spec
  args:
    warn: no
  register: composer_builddep
  until: composer_builddep is success
  retries: 5
  changed_when: "'Nothing to do' in composer_builddep.stdout"

- name: Build RPMs
  command: make -C "{{ item.dir }}" rpm
  args:
    chdir: "{{ item.dir }}"
  loop:
    - project: osbuild
      dir: /opt/osbuild
      enabled: yes
    - project: osbuild-composer
      dir: /opt/osbuild-composer
      enabled: yes
    - project: cockpit-composer
      dir: /opt/cockpit-composer
      enabled: "{{ install_cockpit_composer_from_git }}"
  loop_control:
    label: "{{ item.project }}"
  when: item.enabled
  register: rpm_build
  async: 300
  poll: 0
  changed_when: true

- name: Wait for builds to finish
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ rpm_build.results }}"
  loop_control:
    loop_var: "async_result_item"
  when: async_result_item.item.enabled
  register: async_poll_results
  until: async_poll_results.finished
  retries: 60
  delay: 10

- name: Get a list of RPMs built for osbuild
  command: "find /opt/osbuild/rpmbuild/RPMS/ -name '*.rpm'"
  register: osbuild_packages
  changed_when: false

- name: Get a list of RPMs built for osbuild-composer
  command: "find /opt/osbuild-composer/rpmbuild/RPMS/ -name '*.rpm'"
  register: composer_packages
  changed_when: false

- name: Get a list of RPMs built for cockpit-composer
  command: "find /opt/cockpit-composer/ -name '*.rpm'"
  register: cockpit_packages
  changed_when: false
  when: install_cockpit_composer_from_git

- name: Gather a list of currently installed packages
  package_facts:
    manager: rpm

- name: Set a fact about whether osbuild is installed
  set_fact:
    osbuild_installed: "{{ 'osbuild' in ansible_facts.packages }}"

- name: Disable services before removing old packages
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - cockpit.socket
    - osbuild-composer.socket
    - osbuild-rcm.socket
    - osbuild-composer.service
  when: osbuild_installed

- name: Remove the currently installed packages
  package:
    name:
      - "osbuild-composer*"
      - "osbuild*"
      - "python3-osbuild"
    state: absent
  when: osbuild_installed

- name: List packages to be installed
  debug:
    msg: "{{ composer_packages.stdout_lines + osbuild_packages.stdout_lines + (cockpit_packages.stdout_lines | default([])) }}"

- name: Install RPMs
  package:
    name: "{{ composer_packages.stdout_lines + osbuild_packages.stdout_lines + (cockpit_packages.stdout_lines | default([])) }}"
    state: latest
  changed_when: true

- name: Force upgrade the cockpit-composer RPM
  command: "rpm -Uvh --force {{ item }}"
  args:
    warn: no
  loop: "{{ cockpit_packages.stdout_lines }}"
  changed_when: true
  when: install_cockpit_composer_from_git

- name: Enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - osbuild-rcm.socket
    - osbuild-composer.socket
    - cockpit.socket
