name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: psi

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: date
